name: Mount OSM OBTC

on:
 workflow_call:

jobs:
  genOSM:
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Partner merchants markdown
        id: processVideos
        run: touch merchant.md
             && curl --location 'https://overpass-api.de/api/interpreter' --header 'Content-Type:text/plain' --data '[out:json][timeout:180];area(3600059470)->.brazil;(node[${{ vars.OSM_FILTER }}](area.brazil););out body;>;out skel qt;' > merchant.json  
             && jq -r '.elements[] | "## \(.tags.name // "Unnamed Location")\n**Type:** \(.type)\n**ID:** \(.id)\n**Coordinates:** \(.lat), \(.lon)\n" + ([.tags["addr:street"], .tags["addr:housenumber"], .tags["addr:suburb"], .tags["addr:city"], .tags["addr:postcode"]] | map(select(. != null and . != "")) | join(", ") | if . != "" then "**Address:** " + . + "\n" else "" end) + "**Details:**\n" + (if .tags.PBTC then "\n**PBTC:** ![PBTC](\(.tags.PBTC))" else "" end) + (.tags | to_entries | map(select(.key | test("^(?!addr:|name$|PBTC$).*"))) | map("- **\(.key):** \(.value)") | join("\n"))  + "\n\n**BTCMap:** [View on BTCMap](https://btcmap.org/merchant/node:\(.id)) \n**OpenStreetMap:** [View on OSM](https://www.openstreetmap.org/node/\(.id)) \n"' merchant.json > merchant.md
             && git config --global user.name "juancolchete"
             && git config --global user.email "juancolchete@gmail.com"
             && git add .
             && git commit -m 'chore:add data'
             && git push
